[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fb"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
